name:                 afrp
version:              0.4
visibility:           public
id:                   afrp-0.4-inplace
key:                  afrp-0.4-inplace
license:              LicenseRef-BSD-3
maintainer:           placeholder@example.com
author:               Henrik Nilsson, Antony Courtney
category:             FRP
abi:                  inplace
exposed:              True
exposed-modules:
    AFRP AFRPAffineSpace AFRPDiagnostics AFRPEvent AFRPForceable
    AFRPGeometry AFRPInternals AFRPMergeableRecord AFRPMiscellany
    AFRPPoint2 AFRPPoint3 AFRPTask AFRPUtilities AFRPVector2
    AFRPVector3 AFRPVectorSpace

import-dirs:
    /app/dist-newstyle/build/x86_64-linux/ghc-9.4.7/afrp-0.4/build

library-dirs:
    /app/dist-newstyle/build/x86_64-linux/ghc-9.4.7/afrp-0.4/build

library-dirs-static:
    /app/dist-newstyle/build/x86_64-linux/ghc-9.4.7/afrp-0.4/build

dynamic-library-dirs:
    /app/dist-newstyle/build/x86_64-linux/ghc-9.4.7/afrp-0.4/build

data-dir:             /app/.
hs-libraries:         HSafrp-0.4-inplace
depends:
    array-0.5.4.0 base-4.17.2.0 containers-0.6.7
    random-1.3.1-d85bdf1853bdf6d2661385f28349d0c35802912da7b768619569c066f7d2e44c

haddock-interfaces:
    /app/dist-newstyle/build/x86_64-linux/ghc-9.4.7/afrp-0.4/doc/html/afrp/afrp.haddock

haddock-html:
    /app/dist-newstyle/build/x86_64-linux/ghc-9.4.7/afrp-0.4/doc/html/afrp
